export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const FOLLOWER_REQUEST = "FOLLOWER_REQUEST";
export const FOLLOWER_SUCCESS = "FOLLOWER_SUCCESS";
export const FOLLOWER_FAILURE = "FOLLOWER_FAILURE";

export const GET_FOLLOWER_SUCCESS="GET_FOLLOWER_SUCCESS";